kotlin.code.style = official
org.gradle.jvmargs = -Xmx3G
org.gradle.warning.mode = all
org.gradle.parallel = true
org.gradle.configuration-cache = false

# Check these on https://fabricmc.net/develop/
minecraftVersion = 26.2
loaderVersion = 0.19.5

# Fabric api
fabricVersion = 0.159.0+26.2
loomVersion = 1.16.3
