kotlin.code.style = official
org.gradle.jvmargs = -Xmx3G
org.gradle.warning.mode = all
org.gradle.parallel = true
org.gradle.configuration-cache = false

# Check these on https://fabricmc.net/develop/
minecraftVersion = 26.1
loaderVersion = 0.19.2

# Fabric api
fabricVersion = 0.150.0+26.1.2
loomVersion = 1.16-SNAPSHOT
